server:
  port: 8080
  max-http-header-size: 10485760
  tomcat:
    max-http-post-size: 10485760
    accept-count: 10
    max-connections: 10
    max-threads: 5
    min-spare-threads: 2
    uri-encoding: UTF-8
spring:
  application:
    name: lq-server
  http:
    encoding:
      force: true
      charset: UTF-8
  datasource:
    maximum-pool-size: 20
    max-idle: 20
    max-wait: 10000
    min-idle: 10
    initial-size: 10
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    type: com.alibaba.druid.pool.DruidDataSource

user:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/lq_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root